<?php
/** @var Sheep_Debug_Block_View $this */

$info = $this->getRequestInfo();

$coreHelper = Mage::helper('core');

$databaseConfigurations = $this->getService()->searchConfig('default_setup');

?>
<div class="sf-tabs">
    <div class="tab">
        <h3 class="tab-title"><?php echo $this->__('Queries'); ?></h3>

        <div class="tab-content">
            <h3><?php echo $this->__('SQL Queries'); ?></h3>

            <?php if ($info->getQueries()): ?>
                <table class="alt queries-table">
                    <thead>
                    <tr>
                        <th class="sortable" onclick="sortTable(this, 0, 'queries')"><?php echo $this->__('#'); ?><span class="text-muted">&#9650;</span</th>
                        <th class="nowrap sortable" onclick="sortTable(this, 1, 'queries')"><?php echo $this->__('Time'); ?><span></span></th>
                        <th class="header-info"><?php echo $this->__('Info'); ?></th>
                    </tr>
                    </thead>
                    <tbody id="queries">
                        <?php $row = 0; ?>
                        <?php foreach ($info->getQueries() as $query): ?>
                            <tr>
                                <td class="nowrap"><?php echo $row ?></td>
                                <td class="nowrap"><?php echo sprintf("%.2f", $query->getElapsedSecs() * 1000) ?> <?php echo $this->__('ms'); ?></td>
                                <td>
                                    <pre><code class="sql"><?php echo $this->escapeHtml($query->getQuery()) ?></code></pre>

                                    <?php if ($query->getQueryParams()): ?>
                                    <div>
                                        <strong class="font-normal text-small"><?php echo $this->__('Parameters:'); ?></strong>
                                        <?php echo $this->renderArrayAsText($query->getQueryParams()) ?>
                                    </div>
                                    <?php endif; ?>

                                    <div class="text-small font-normal">
                                        <?php if ($query->getQueryType() == Zend_Db_Profiler::SELECT): ?>
                                                <a class="link-inverse"
                                                   href="<?php echo Mage::helper('sheep_debug/url')->getSelectQueryUrl($info->getToken(), $row) ?>"
                                                   onclick="return fetchData(this);"
                                                   title="<?php echo $this->__('Select Query'); ?>"
                                                   data-target-id="select-<?php echo $row ?>">
                                                    <?php echo $this->__('Select Query'); ?>
                                                </a>
                                                &nbsp; &nbsp;
                                                <a class="link-inverse"
                                                   href="<?php echo Mage::helper('sheep_debug/url')->getExplainQueryUrl($info->getToken(), $row) ?>"
                                                   onclick="return fetchData(this);"
                                                   title="<?php echo $this->__('Explain Query'); ?>"
                                                   data-target-id="explain-<?php echo $row ?>">
                                                    <?php echo $this->__('Explain Query'); ?>
                                                </a>
                                        <?php endif; ?>

                                        <?php if ($query->getStacktrace()): ?>
                                            &nbsp; &nbsp;
                                            <a class="link-inverse"
                                               href="<?php echo Mage::helper('sheep_debug/url')->getQueryStacktraceUrl($info->getToken(), $row) ?>"
                                               onclick="return fetchData(this);"
                                               title="<?php echo $this->__('Show Stacktrace'); ?>"
                                               data-target-id="stacktrace-<?php echo $row ?>">
                                                <?php echo $this->__('Show Stacktrace'); ?>
                                            </a>
                                        <?php endif; ?>
                                    </div>

                                    <div class="query-results" id="select-<?php echo $row ?>"></div>
                                    <div class="query-explain" id="explain-<?php echo $row ?>"></div>
                                    <div id="stacktrace-<?php echo $row ?>"></div>
                                </td>
                            </tr>
                            <?php $row++; ?>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <?php else: ?>
                <?php if ($info->getModelsAsArray()): ?>
                    <p class="label status-warning"><strong><?php echo $this->__('You need to enable SQL Profiler to capture executed SQL queries.'); ?></strong></p>
                <?php endif; ?>

                <div class="empty"><?php echo $this->__('No database queries were performed.'); ?></div>
            <?php endif; ?>
        </div>
    </div>

    <div class="tab">
        <h3 class="tab-title"><?php echo $this->__('Models'); ?></h3>

        <div class="tab-content">
            <h3><?php echo $this->__('Response Headers'); ?></h3>
            <?php echo $this->renderArrayFields($info->getModelsAsArray()) ?>
        </div>
    </div>

    <div class="tab">
        <h3 class="tab-title"><?php echo $this->__('Collections'); ?></h3>

        <div class="tab-content">
            <h3><?php echo $this->__('Loaded Collections'); ?></h3>

            <?php if ($info->getCollections()): ?>
                <p class="help"><?php echo $this->__('Collections loaded during this request.'); ?></p>

                <table id="collections-table" class="alt">
                    <thead>
                    <tr>
                        <th><?php echo $this->__('#'); ?></th>
                        <th><?php echo $this->__('Type'); ?></th>
                        <th class="header-info"><?php echo $this->__('Class'); ?></th>
                        <th><?php echo $this->__('Count'); ?></th>
                    </tr>
                    </thead>

                    <tbody id="collections">
                    <?php $row = 0; ?>
                    <?php foreach ($info->getCollections() as $collection): ?>
                        <tr>
                            <td><?php echo ++$row ?></td>
                            <td><?php echo $collection->getType() ?></td>
                            <td><?php echo $collection->getClass() ?></td>
                            <td><?php echo $this->formatNumber($collection->getCount(), 0) ?></td>
                        </tr>
                        <tr>
                            <td colspan="4" class="wrap">
                                <pre>
                                    <code class="sql">
                                        <?php echo $this->escapeHtml($collection->getQuery()); ?>
                                    </code>
                                </pre>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            <?php else: ?>
                <div class="empty"><?php echo $this->__('No collections were loaded.'); ?></div>
            <?php endif; ?>
        </div>
    </div>

    <div class="tab">
        <h3 class="tab-title"><?php echo $this->__('Database Configuration'); ?></h3>

        <div class="tab-content">
            <p class="help"><?php echo $this->__('Current configurations related to database.'); ?></p>
            <?php echo $this->renderArray($databaseConfigurations); ?>
        </div>
    </div>

</div>
