<?php
/** @var Sheep_Debug_Block_View $this */

$info = $this->getRequestInfo();

$events = $info->getEvents();
$observers = $info->getObservers();

?>
<h2><?php echo $this->__('Events'); ?></h2>

<div class="sf-tabs">
    <div class="tab">
        <h3 class="tab-title <?php if(!$events): ?>disabled<?php endif; ?>">
            <?php echo $this->__('Events'); ?>
            <span class="badge"><?php echo count($events) ?></span>
        </h3>

        <div class="tab-content">
            <h3><?php echo $this->__('Events'); ?></h3>
            <p class="help">All events raised during request.</p>

            <?php echo $this->renderArrayFields($events) ?>
        </div>
    </div>

    <div class="tab">
        <h3 class="tab-title <?php if(!$observers): ?>disabled<?php endif; ?>">
            <?php echo $this->__('Observers'); ?>
            <span class="badge"><?php echo count($observers) ?></span>
        </h3>

        <div class="tab-content">
            <h3><?php echo $this->__('Observers'); ?></h3>
            <p class="help">All observers executed during current request.</p>

            <?php echo $this->renderArrayFields($observers) ?>
        </div>
    </div>

</div>
