<?php
$templateDirs = $this->getTemplateDirs();
$blocks = $this->getItems();
?>

<h4><?php echo $this->__('Template path') ?></h4>
<?php if( $templateDirs ): ?>
	<ol>
	<?php foreach( $templateDirs as $template ): ?>
		<li><?php echo $template; ?></li>
	</ol>
	<?php endforeach; ?>
<?php else: ?>
	<p>None</p>
<?php endif; ?>

<h4><?php echo $this->__('Blocks') ?></h4>
<table>
	<thead>
		<tr>
			<th>#</th>
			<th><?php echo $this->__('Name In Layout') ?></th>
			<th><?php echo $this->__('Block Class') ?></th>
			<th><?php echo $this->__('Template') ?></th>
		</tr>
	</thead>
	<tbody>
		<?php $row = 0; ?>
		<?php foreach( $blocks as $block ): ?>
			<tr class="<?php echo ( ($row % 2 ? 'djDebugOdd' : 'djDebugEven')) ?>">
                <td><?php echo $row ?></td>
                <td><?php echo $block['layout_name'] ?></td>
                <td><?php echo $block['class'] ?></td>
                <td>
                <?php if($block['template']):?> 
                    <a class="remoteCall toggleTemplate" href="<?php echo Mage::getUrl('debug/index/viewTemplate', array('_query' => array('template'=> $block['template']))) ?>"><?php echo $block['template'] ?></a>
                <?php endif; ?>
                </td>
			</tr>
			<?php $row++; ?>
		<?php endforeach ?>
	</tbody>
</table>

