<?php /* @var $this Magneto_Debug_Block_Config */ ?>
<dl>
	<dt><strong>
		<a class="toggleTemplate" href="<?php echo $this->getToggleHintsUrl() ?>">
            <?php echo $this->__('Toggle Template Hints') ?>
		</a>
		<a class="toggleTemplate" href="<?php echo $this->getToggleTranslateHintsUrl() ?>">
            <?php echo $this->__('Toggle Translate Inline') ?>
		</a>
        <?php if ($this->hasFullPageCache()): ?>
        <a class="toggleTemplate" href="<?php echo $this->getFullPageDebugUrl() ?>">
            <?php echo $this->__('Toggle FPC Debug') ?>
        </a>
        <?php endif ?>
	</strong></dt>
</dl>
<dl>
	<dt><strong>
		<a class="toggleTemplate" href="<?php echo $this->getDownloadConfigUrl() ?>" target="_blank">Download Config (XML)</a>
	</strong>
    <strong>
		<a class="toggleTemplate" href="<?php echo $this->getDownloadConfigAsTextUrl() ?>" target="_blank">Download Config (TEXT)</a>
	</strong></dt>
</dl>
<br/>

<form action="#" id="config-search-form" onSubmit="handlerFunction(); return false;">
    <input name="query" class="input-text required-entry" type="search" size="40" />
    <input type="button" onClick="handlerFunction()" value="<?php echo $this->__('Search Config') ?>" />
</form>
<p>
Search examples: <em>default/system</em>, <em>global/resources/default_setup</em>, <em>frontend/events</em> or <em>modules</em>. If you don't know what to search check all the <a class="toggleTemplate" href="<?php echo $this->getDownloadConfigAsTextUrl() ?>" target="_blank">configuration keys</a>.
</p>

<script type="text/javascript">
function handlerFunction(){
    var request = new Ajax.Updater(
        'config-search-results',
        '<?php echo $this->getSearchConfigUrl() ?>',
        {
            method: 'post',
            parameters: Form.serialize($('config-search-form'))
        });
}
</script>
<div id="config-search-results">
<table>
	<thead>
		<tr>
            <th><?php echo $this->__("#") ?></th>
            <th><?php echo $this->__("Config") ?></th>
            <th><?php echo $this->__("Value") ?></th>
		</tr>
	</thead>
    <tbody>
	</tbody>
</table>
</div>
