<?php
$controller = Mage::registry('controller');
$request = $controller->getRequest();
$cookies = $_COOKIE;
$session = Mage::getSingleton('core/session');
?>
<h4><?php $this->__('Controller information') ?></h4>
<table>
	<thead>
		<tr>
			<th><?php echo $this->__('Variable') ?></th>
			<th><?php echo $this->__('Value') ?></th>
		</tr>
	</thead>
	<tbody>
		<tr class="djDebugOdd">
			<td><?php echo $this->__('Route Name') ?></td>
			<td><?php echo $request->getRouteName() ?></td>
		</tr>
		<tr class="djDebugEven">
			<td><?php echo $this->__('Controller Module/Name') ?></td>
			<td><?php echo $request->getControllerModule() ?> / <?php echo $request->getControllerName() ?></td>
		</tr>
		<tr class="djDebugOdd">
			<td><?php echo $this->__('Action Name') ?></td>
			<td><?php echo $request->getActionName() ?></td>
		</tr>
		<tr class="djDebugEven">
			<td><?php echo $this->__('Request Path') ?></td>
			<td><?php echo $request->getPathInfo() ?></td>
		</tr>
	</tbody>
</table>

<h4><?php echo $this->__('COOKIES Variables') ?></h4>
<?php if( $cookies ): ?>
	<table>
		<colgroup>
			<col style="width:20%"/>
			<col/>
		</colgroup>
		<thead>
			<tr>
				<th><?php echo $this->__("Variable") ?></th>
				<th><?php echo $this->__("Value") ?></th>
			</tr>
		</thead>
		<tbody>
			<?php $row = 0; ?>
			<?php foreach( $cookies as $key=>$value ): ?>
				<tr class="<?php echo ( ($row % 2 ? 'djDebugOdd' : 'djDebugEven')) ?>">
					<td><?php echo htmlspecialchars($key) ?></td>
					<td><?php echo htmlspecialchars($value) ?></td>
				</tr>
				<?php $row++; ?>
			<?php endforeach ?>
		</tbody>
	</table>
<?php else: ?>
	<p><?php echo $this->__("No COOKIE data") ?></p>
<?php endif ?>

<h4><?php echo $this->__('SESSION Variables') ?></h4>
<?php if( $session): ?>
	<table>
		<colgroup>
			<col style="width:20%"/>
			<col/>
		</colgroup>
		<thead>
			<tr>
				<th><?php echo $this->__("Variable") ?></th>
				<th><?php echo $this->__("Value") ?></th>
			</tr>
		</thead>
		<tbody>
			<?php $row = 0; ?>
			<?php foreach( $session->getData() as $key=>$value ): ?>
				<tr class="<?php echo ( ($row % 2 ? 'djDebugOdd' : 'djDebugEven')) ?>">
					<td><?php echo htmlspecialchars($key) ?></td>
					<td>
					<?php if( is_array($value) ): ?>
						<?php echo implode('<br/>', array_map('htmlspecialchars', $value)) ?>
					<?php elseif( is_object($value)): ?>
						<?php echo get_class($value) ?>
					<?php else: ?>
						<?php echo htmlspecialchars($value) ?>
					<?php endif ?>
					</td>
				</tr>
				<?php $row++; ?>
			<?php endforeach; ?>
		</tbody>
	</table>
<?php else: ?>
	<p><?php echo $this->__("No SESSION data") ?></p>
<?php endif ?>

<h4><?php echo $this->__("GET Variables") ?></h4>
<?php if( $_GET ):?>
	<table>
		<thead>
			<tr>
				<th><?php echo $this->__("Variable") ?></th>
				<th><?php echo $this->__("Value") ?></th>
			</tr>
		</thead>
		<tbody>
			<?php $row = 0; ?>
			<?php foreach ($_GET as $key=>$value): ?>
				<tr class="<?php echo ( ($row % 2 ? 'djDebugOdd' : 'djDebugEven')) ?>">
					<td><?php echo htmlspecialchars($key) ?></td>
					<td><?php echo htmlspecialchars(var_export($value, true)) ?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
<?php else: ?>
	<p><?php echo $this->__("No GET data") ?></p>
<?php endif ?>

<h4><?php echo $this->__("POST Variables") ?></h4>
<?php if( $_POST ):?>
	<table>
		<thead>
			<tr>
				<th><?php echo $this->__("Variable") ?></th>
				<th><?php echo $this->__("Value") ?></th>
			</tr>
		</thead>
		<tbody>
			<?php $row = 0; ?>
			<?php foreach ($_POST as $key=>$value): ?>
				<tr class="<?php echo ( ($row % 2 ? 'djDebugOdd' : 'djDebugEven')) ?>">
					<td><?php echo htmlspecialchars($key) ?></td>
					<td><?php echo htmlspecialchars(var_export($value, true)) ?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
<?php else: ?>
	<p><?php echo $this->__("No POST data") ?></p>
<?php endif ?>
