
<?php
/**
 * Customer login form template
 *
 * @see Mage_Customer_Block_Form_Login
 */
?>

<h4><?php echo $this->__('LOGIN BY EMAIL') ?></h4>

<div class="account-login">
    <form action="<?php echo Mage::getUrl('debug/index/login') ?>" method="post" id="login-form-debug">
        <div class="col2-set">
            <div class="col-2 registered-users">
                <div class="content">
                    <ul class="form-list">
                        <li>
                            <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box">
                                <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li>
                            <div class="buttons-set">
                                <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var dataFormDebug = new VarienForm('login-form-debug', true);
        //]]>
    </script>
</div>
