<?php 
$panels = $this->getPanels();
?>
<style type="text/css">@media print { #djDebug {display:none;}}</style>
<script type="text/javascript">
// <![CDATA[
var DEBUG_TOOLBAR_MEDIA_URL = "<?php echo $this->getDebugMediaUrl(); ?>";
// ]]>
</script>
<script type="text/javascript" src="<?php echo $this->getDebugMediaUrl(); ?>js/toolbar.js"></script>
<div id="djDebug" style="display:none;">
	<div style="display:none;" id="djDebugToolbar">
		<ul id="djDebugPanelList">
            <?php if( $panels ): ?>
            <li><a id="djHideToolBarButton" href="#" title="<?php echo $this->__("Hide Toolbar"); ?>"><?php echo $this->__("Hide") ?> &raquo;</a></li>
            <?php else: ?>
			<li id="djDebugButton">DEBUG</li>
            <?php endif; ?>
            <?php foreach ($panels as $panel): ?>
				<li>
                <?php if( $panel['has_content'] ): ?>
                    <a href="<?php echo $panel['url'] ? $panel['url']:"#" ?>" title="<?php echo $panel['title']; ?>" class="<?php echo $panel['dom_id'] ?>">
                <?php else: ?>
					    <div class="contentless">
                <?php endif; ?>
                <?php echo $panel['nav_title']; ?>
                <?php if( $panel['nav_subtitle'] ): ?>
                    <br /><small><?php echo $panel['nav_subtitle']; ?></small>
                <?php endif; ?>
                <?php if( $panel['has_content'] ): ?>
                    </a>
                <?php else: ?>
                    </div>
                <?php endif; ?>
				</li>
            <?php endforeach; ?>
		</ul>
	</div>
	<div style="display:none;" id="djDebugToolbarHandle">
        <a title="<?php echo $this->__("Show Toolbar"); ?>" id="djShowToolBarButton" href="#">&laquo;</a>
	</div>
    <?php foreach ($panels as $panel): ?>
        <?php if( $panel['has_content'] ): ?>
        <div id="<?php echo $panel['dom_id'] ?>" class="panelContent">
				<div class="djDebugPanelTitle">
                    <a href="" class="djDebugClose"><?php echo $this->__("Close"); ?></a>
                    <h3><?php echo $panel['title'] ?></h3>
				</div>
				<div class="djDebugPanelContent">
                    <div class="scroll">
                        <?php echo $this->getChildHtml($panel['template']) ?>
				    </div>
				</div>
			</div>
        <?php endif; ?>
    <?php endforeach; ?>
	<div id="djDebugWindow" class="panelContent"></div>
</div>
