<?php
$layout =  Mage::getSingleton('core/layout');
$layoutHandles = Mage::getSingleton('core/layout')->getUpdate()->getHandles();
$layoutUpdates = Mage::getSingleton('core/layout')->getUpdate()->asArray();
?>

<h4><?php echo $this->__('Handles for this request'); echo "(" . count($layoutHandles) . ")" ?></h4>
<table>
	<thead>
		<tr>
			<th><?php echo $this->__('Handle') ?></th>
		</tr>
	</thead>
	<tbody>
		<?php $row = 0; ?>
		<?php foreach( $layoutHandles as $item ): ?>
			<tr class="<?php echo ( ($row % 2 ? 'djDebugOdd' : 'djDebugEven')) ?>">
                <td><a class="remoteCall toggleTemplate" href="<?php echo $this->getUrl('debug/index/viewFilesWithHandle', array('layout' => $item)) ?>"><?php echo $item ?></a></td>
			</tr>
			<?php $row++; ?>
		<?php endforeach ?>
	</tbody>
</table>

<dl>
    <dt><strong>Page Layout</strong></dt>
    <dd>
		<div class="djTemplateShowContextDiv"><a class="djTemplateShowContext"><span class="toggleArrow">&#x25B6;</span>View Page Layout</a></div>
        <div class="djTemplateHideContextDiv" style="display:none;">
            <code><?php echo htmlspecialchars($layout->getNode()->asXML()) ?></code>
        </div>
	</dd>
</dl>

<h4><?php echo $this->__('Layout updates') ?> (<?php echo count($layoutUpdates); ?>)</h4>
<table>
	<thead>
		<tr>
			<th><?php echo $this->__('#'); ?></th>
			<th><?php echo $this->__('Update') ?></th>
		</tr>
	</thead>
	<tbody>
		<?php $row = 0; ?>
		<?php foreach( $layoutUpdates as $item ): ?>
			<tr class="<?php echo ( ($row % 2 ? 'djDebugOdd' : 'djDebugEven')) ?>">
			<td><?php echo $row ?>.</td>
			<td class="syntax">
				<code><?php echo htmlspecialchars($item) ?></code>
				</td>
			</tr>
			<?php $row++; ?>
		<?php endforeach ?>
	</tbody>
</table>

