<?php
?>
<h4><?php echo $this->__('Grouped Class Search'); ?></h4>
<form action="#" id="class-search-form" onSubmit="submitGroupedClassSearch(); return false;">
    <input name="uri" class="input-text required-entry" type="search" size="40" />
    <select name="group" class="input-select required-entry">
        <option value="all"><?php echo $this->__('all'); ?></option>
        <option value="model"><?php echo $this->__('model'); ?></option>
        <option value="block"><?php echo $this->__('block'); ?></option>
        <option value="helper"><?php echo $this->__('helper'); ?></option>
    </select>
    <input type="button" onClick="submitGroupedClassSearch()" value="<?php echo $this->__('Search Grouped Class Name') ?>" />
</form>
<p>
<?php echo $this->__('Search examples:'); ?> <em>catalog/product</em>, <em>core/url</em>, <?php echo $this->__('etc.'); ?>
</p>

<script type="text/javascript">
function submitGroupedClassSearch(){
    var request = new Ajax.Updater(
        'class-search-results',
        '<?php echo $this->getUrl("debug/index/searchGroupedClass") ?>',
        {
            method: 'post',
            parameters: Form.serialize($('class-search-form'))
        });
}
</script>
<div id="class-search-results">
<table>
	<thead>
		<tr>
            <th><?php echo $this->__('#') ?></th>
            <th><?php echo $this->__('Group Type') ?></th>
            <th><?php echo $this->__('Class') ?></th>
            <th><?php echo $this->__('File path') ?></th>
		</tr>
	</thead>
    <tbody>
	</tbody>
</table>
</div>
