<?php
?>
<h4>Grouped Class Search</h4>
<form action="#" id="class-search-form" onSubmit="submitGroupedClassSearch(); return false;">
    <input name="uri" class="input-text required-entry" type="search" size="40" />
    <select name="group" class="input-select required-entry">
        <option>all</option>
        <option>model</option>
        <option>block</option>
        <option>helper</option>
    </select>
    <input type="button" onClick="submitGroupedClassSearch()" value="<?php echo $this->__('Search Grouped Class Name') ?>" />
</form>
<p>
Search examples: <em>catalog/product</em>, <em>core/url</em>, etc.
</p>

<script type="text/javascript">
function submitGroupedClassSearch(){
    var request = new Ajax.Updater(
        'class-search-results',
        '<?php echo $this->getUrl("debug/index/searchGroupedClass") ?>',
        {
            method: 'post',
            parameters: Form.serialize($('class-search-form'))
        });
}
</script>
<div id="class-search-results">
<table>
	<thead>
		<tr>
            <th><?php echo $this->__("#") ?></th>
            <th><?php echo $this->__("Group Type") ?></th>
            <th><?php echo $this->__("Search Results") ?></th>
		</tr>
	</thead>
    <tbody>
	</tbody>
</table>
</div>
