<table>
	<thead>
		<tr>
            <th><?php echo $this->__("Package") ?></th>
            <th><?php echo $this->__("Version") ?></th>
		</tr>
	</thead>
    <tbody>
        <?php $row = 0; ?>
        <?php foreach( $this->getItems() as $item ): ?>
            <tr class="<?php echo (($row % 2)?'djDebugOdd':'djDebugEven') ?>">
                <td><?php echo $item[0] ?></td>
                <td><?php echo $item[1] ?></td>
			</tr>
            <?php $row++; ?>
        <?php endforeach; ?>
	</tbody>
</table>
