<?php
/** @var Sheep_Debug_Block_Controller $this */

$info = $this->getController();
$cookies = $info->getCookies();
$session = $info->getSession();
$getParameters = $info->getGetParameters();
$postParameters = $info->getPostParameters();

?>

<div class="sf-toolbar-block">
    <a href="<?php echo $this->getRequestViewUrl() ?>#controller">
        <div class="sf-toolbar-icon">
            <span
                class="sf-toolbar-status sf-toolbar-status-<?php echo $this->getStatusColor() ?>">
                <?php echo $this->getResponseCode() ?>
            </span>
            <span class="sf-toolbar-value">@</span>
            <span class="sf-toolbar-label"><?php echo $this->escapeHtml($info->getRouteName()) ?></span>
        </div>
    </a>
    <div class="sf-toolbar-info">
        <div class="sf-toolbar-info-piece">
            <b><?php echo $this->__('HTTP Status'); ?></b>
            <span><?php echo $this->getResponseCode() ?></span>
        </div>

        <div class="sf-toolbar-info-piece">
            <b><?php echo $this->__('Module'); ?></b>
            <span><?php echo $info->getModule() ?></span>
        </div>

        <div class="sf-toolbar-info-piece">
            <b><?php echo $this->__('Controller'); ?></b>
            <span><?php echo $info->getReference() ?></span>
        </div>
    </div>
</div>

