<?php
/* @var $this Sheep_Debug_Block_Layout */

$info = $this->getRequestInfo();
$design = $info->getDesign();
$layoutHandles = $design->getLayoutHandles();
$layoutUpdates = $design->getLayoutUpdates();
$blocks = $info->getBlocks();
?>

<div class="sf-toolbar-block">
    <a href="<?php echo $this->getRequestViewUrl('layout') ?>">
        <div class="sf-toolbar-icon">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" height="24" viewBox="0 0 24 24" enable-background="new 0 0 24 24" xml:space="preserve">
                <path fill="#AAAAAA" d="M20.1,1H3.9C2.3,1,1,2.3,1,3.9v16.3C1,21.7,2.3,23,3.9,23h16.3c1.6,0,2.9-1.3,2.9-2.9V3.9
    C23,2.3,21.7,1,20.1,1z M21,20.1c0,0.5-0.4,0.9-0.9,0.9H3.9C3.4,21,3,20.6,3,20.1V3.9C3,3.4,3.4,3,3.9,3h16.3C20.6,3,21,3.4,21,3.9
    V20.1z M5,5h14v3H5V5z M5,10h3v9H5V10z M10,10h9v9h-9V10z">
                </path>
            </svg>
            <span class="sf-toolbar-value"><?php echo sprintf('%0.0f', $this->getRequestInfo()->getRenderingTime()) ?></span>
            <span class="sf-toolbar-label"><?php echo $this->__('ms'); ?></span>
        </div>
    </a>

    <div class="sf-toolbar-info">
        <div class="sf-toolbar-info-group">
            <div class="sf-toolbar-info-piece">
                <b><?php echo $this->__('Design Area'); ?></b>
                <span><?php echo $this->escapeHtml($design->getArea()) ?></span>
            </div>

            <div class="sf-toolbar-info-piece">
                <b><?php echo $this->__('Package Name'); ?></b>
                <span><?php echo $this->escapeHtml($design->getPackageName()) ?></span>
            </div>

            <div class="sf-toolbar-info-piece">
                <b><?php echo $this->__('Template Theme'); ?></b>
                <span><?php echo $this->escapeHtml($design->getThemeTemplate()) ?></span>
            </div>
        </div>

        <div class="sf-toolbar-info-group">
            <div class="sf-toolbar-info-piece">
                <b><?php echo $this->__('Handles'); ?></b>
                <span><?php echo count($layoutHandles) ?></span>
            </div>

            <div class="sf-toolbar-info-piece">
                <b><?php echo $this->__('Layout Updates'); ?></b>
                <span><?php echo count($layoutUpdates) ?></span>
            </div>

            <div class="sf-toolbar-info-piece">
                <b><?php echo $this->__('Blocks'); ?></b>
                <span><?php echo count($blocks) ?></span>
            </div>
        </div>
    </div>
</div>

