<?php
/* @var $this Sheep_Debug_Block_Models */

$coreHelper = Mage::helper('core');

$models = $this->getSortedModels();
$collections = $this->getSortedCollections();
$queries = $this->getQueries();
?>

<div class="sf-toolbar-block">
    <a href="<?php echo $this->getRequestViewUrl() ?>#models">
        <div class="sf-toolbar-icon">
            <span class="sf-toolbar-value"><?php echo count($queries) ?></span>
            <span class="sf-toolbar-label"><?php echo $this->__('queries'); ?></span>
        </div>
    </a>
    <div class="sf-toolbar-info">
        <div class="sf-toolbar-info-group">
            <div class="sf-toolbar-info-piece">
                <b><?php echo $this->__('Models'); ?></b>
                <span><?php echo count($models) ?></span>
            </div>

            <div class="sf-toolbar-info-piece">
                <b><?php echo $this->__('Collections'); ?></b>
                <span><?php echo count($collections) ?></span>
            </div>

            <div class="sf-toolbar-info-piece">
                <b><?php echo $this->__('Queries'); ?></b>
                <span><?php echo count($queries) ?></span>
            </div>
        </div>

        <div class="sf-toolbar-info-group">
            <div class="sf-toolbar-info-piece">
                <b><?php echo $this->__('SQL Profiler Status'); ?></b>
                <?php if ($this->isSqlProfilerEnabled()): ?>
                    <span class="sf-toolbar-status sf-toolbar-status-green">on</span>
                <?php else: ?>
                    <span class="sf-toolbar-status sf-toolbar-status-red">off</span>
                <?php endif ?>
            </div>
        </div>
</div>

