<?php
/** @var Sheep_Debug_Block_Modules $this */
?>
<table>
    <thead>
    <tr>
        <th><?php echo $this->__('Module') ?></th>
        <th><?php echo $this->__('Version') ?></th>
        <th><?php echo $this->__('Status') ?></th>
        <th><?php echo $this->__('Actions') ?></th>
    </tr>
    </thead>
    <tbody>
    <?php $row = 0; ?>
    <?php foreach ($this->getModules() as $item): ?>
        <tr class="<?php echo(($row % 2) ? 'djDebugOdd' : 'djDebugEven') ?>">
            <td><?php echo $this->escapeHtml($item['module']) ?></td>
            <td><?php echo $this->escapeHtml($item['version']) ?></td>
            <td><?php echo $item['active'] ? $this->__('Active') : $this->__('Disabled') ?></td>
            <td>
                <?php if ($item['active']): ?>
                    <a href="<?php echo $this->getDisableModuleUrl($item['module']) ?>">
                        <?php echo $this->__('Disable'); ?>
                    </a>
                <?php else: ?>
                    <a href="<?php echo $this->getEnableModuleUrl($item['module']) ?>">
                        <?php echo $this->__('Enable'); ?>
                    </a>
                <?php endif; ?>
            <td>
        </tr>
        <?php $row++; ?>
    <?php endforeach; ?>
    </tbody>
</table>
