<?php
/** @var Sheep_Debug_Block_Util $this */
?>

<div class="sf-toolbar-block sf-toolbar-block-config  sf-toolbar-block-right">
    <a href="<?php echo $this->getRequestViewUrl('utilities') ?>">
        <div class="sf-toolbar-icon">
            <span class="sf-toolbar-label">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" height="24" viewBox="0 0 24 24"
                     xml:space="preserve">
                    <path fill="#AAAAAA"
                          d="m 2.571,17.5 18.859,0 c 0.87,0 1.57,0.7 1.57,1.57 l 0,1.57 c 0,0.87 -0.7,1.57 -1.57,1.57 l -18.859,0 C 1.702,22.21 1,21.51 1,20.64 L 1,19.07 C 1,18.2 1.702,17.5 2.571,17.5 Z M 1,11.21 1,12.79 c 0,0.86 0.702,1.56 1.571,1.56 l 18.859,0 c 0.87,0 1.57,-0.7 1.57,-1.56 l 0,-1.58 C 23,10.35 22.3,9.644 21.43,9.644 l -18.859,0 C 1.702,9.644 1,10.35 1,11.21 Z M 1,3.357 1,4.929 c 0,0.869 0.702,1.572 1.571,1.572 l 18.859,0 C 22.3,6.501 23,5.798 23,4.929 L 23,3.357 C 23,2.489 22.3,1.786 21.43,1.786 l -18.859,0 C 1.702,1.786 1,2.489 1,3.357 Z"/>
                </svg>
            </span>
            <span class="sf-toolbar-value"><?php echo $this->__('Tools'); ?></span>
        </div>
    </a>

    <div class="sf-toolbar-info">
        <div class="sf-toolbar-info-piece">
            <b><?php echo $this->__('Cache'); ?></b>
            <span>
                <a href="<?php echo $this->getFlushCacheUrl() ?>"><?php echo $this->__('Flush'); ?></a>
            </span>
        </div>

        <?php if ($this->hasFullPageCache()): ?>
        <div class="sf-toolbar-info-piece">
            <b><?php echo $this->__('Full Page Cache Hints'); ?></b>
            <span>
                <?php if ($this->isFPCDebugEnabled()): ?>
                    <a href="<?php echo $this->getDisableFPCDebugUrl() ?>"><?php echo $this->__('Disable'); ?></a>
                <?php else: ?>
                    <a href="<?php echo $this->getEnableFPCDebugUrl() ?>"><?php echo $this->__('Enable'); ?></a>
                <?php endif; ?>
            </span>
        </div>
        <?php endif; ?>

        <div class="sf-toolbar-info-piece">
            <b><?php echo $this->__('Template Hints'); ?></b>
            <span>
                <?php if ($this->isTemplateHintsEnabled()): ?>
                    <a href="<?php echo $this->getDisableTemplateHintsUrl() ?>"><?php echo $this->__('Disable'); ?></a>
                <?php else: ?>
                    <a href="<?php echo $this->getEnableTemplateHintsUrl() ?>"><?php echo $this->__('Enable'); ?></a>
                <?php endif; ?>
            </span>
        </div>

        <div class="sf-toolbar-info-piece">
            <b><?php echo $this->__('SQL Profiler'); ?></b>
            <span>
                <?php if ($this->isSqlProfilerEnabled()): ?>
                    <a href="<?php echo $this->getDisableSqlProfilerUrl() ?>"><?php echo $this->__('Disable'); ?></a>
                <?php else: ?>
                    <a href="<?php echo $this->getEnableSqlProfilerUrl() ?>"><?php echo $this->__('Enable'); ?></a>
                <?php endif; ?>
            </span>
        </div>

        <div class="sf-toolbar-info-piece">
            <b><?php echo $this->__('Varien Profiler'); ?></b>
            <span>
                <?php if ($this->isVarienProfilerEnabled()): ?>
                    <a href="<?php echo $this->getDisableVarienProfilerUrl() ?>"><?php echo $this->__('Disable'); ?></a>
                <?php else: ?>
                    <a href="<?php echo $this->getEnableVarienProfilerUrl() ?>"><?php echo $this->__('Enable'); ?></a>
                <?php endif; ?>
            </span>
        </div>

        <div class="sf-toolbar-info-piece">
            <b><?php echo $this->__('Inline Translation'); ?></b>
            <span>
                <?php if ($this->isTranslateInlineEnable()): ?>
                    <a href="<?php echo $this->getDisableTranslateUrl() ?>"><?php echo $this->__('Disable'); ?></a>
                <?php else: ?>
                    <a href="<?php echo $this->getEnableTranslateUrl() ?>"><?php echo $this->__('Enable'); ?></a>
                <?php endif; ?>
            </span>
        </div>

        <div class="sf-toolbar-info-piece">
            <b><?php echo $this->__('Persist Request Profile'); ?></b>
            <span>
                <a href="#" onclick="sheepDebugCookie.togglePersistence()" id="sheep-debug-toggle-persist"><?php echo $this->isDisablePersistenceCookieOn() ? $this->__('Enable') : $this->__('Disable'); ?></a>
            </span>
        </div>
    </div>
</div>
<script>
    var sheepDebugCookie = new SheepDebug.PersistCookie('<?php echo 'sheep_debug_disable_persist' ?>', 'sheep-debug-toggle-persist');
</script>
