<div class="djDebugPanelTitle"> 
    <a class="djDebugClose djDebugBack" href="">"Back"</a> 
    <h3><?php echo $title ?></h3> 
</div> 

<div class="djDebugPanelContent">
    <div class="scroll">
        <dl>
            <dt><?php echo $this->__("Executed SQL") ?></dt>
            <dd><?php echo htmlspecialchars($query); ?></dd>
        </dl>

        <table class="djSqlExplain">
            <thead>
                <tr>
                    <?php foreach( $headers as $header ): ?>
                        <th><?php echo htmlspecialchars($header); ?></th>
                    <?php endforeach; ?>
                </tr>
            </thead>
            <tbody>
               <?php $row=0; ?>
               <?php foreach( $items as $row ): ?>
                <tr class="<?php echo ( ($row % 2 ? 'djDebugOdd' : 'djDebugEven')) ?>">
                    <?php foreach( $row as $key => $value ): ?>
                        <td><?php echo htmlspecialchars($value); ?></td>
                    <?php endforeach; ?>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

