<table>
	<thead>
		<tr>
            <th><?php echo $this->__("#") ?></th>
            <th><?php echo $this->__("Config") ?></th>
            <th><?php echo $this->__("Value") ?></th>
		</tr>
	</thead>
    <tbody>
        <div id="config-search-results">
        <?php if(count($items)): ?>
            <?php $row=0 ?>
            <?php foreach($items as $key=>$value): ?>
                <tr>
                    <td><?php echo $row ?></td>
                    <td><?php echo $key ?></td>
                    <td><?php echo htmlspecialchars($value) ?></td>
                </tr>
                <?php $row++ ?>
            <?php endforeach; ?>
        <?php else: ?>
            <tr><td colspan="3">Configurations not found for this query.</td></tr>
        <?php endif; ?>
        </div>
	</tbody>
</table>
