<?php
/* @var $this Sheep_Debug_Block_Config */
?>

<h4><?php echo $this->__('something here'); ?></h4>
<p>
    <button class="button" onclick="window.location.href = '<?php echo $this->getDownloadConfigAsTextUrl() ?>'">
        <?php echo $this->__('Download Config (TEXT)'); ?>
    </button>
    <button class="button" onclick="window.location.href = '<?php echo $this->getDownloadConfigAsXmlUrl() ?>'">
        <?php echo $this->__('Download Config (XML)'); ?>
    </button>
</p>

<h4><?php echo $this->__('Configuration Search'); ?></h4>

<form action="#" id="config-search-form" onSubmit="searchConfiguration(); return false;">
    <input name="query" class="input-text required-entry" type="search" size="40"/>
    <button class="button" onClick="handlerFunction()"><?php echo $this->__('Search Config') ?></button>
</form>

<p>
    Search examples: <em>default/system</em>, <em>global/resources/default_setup</em>, <em>frontend/events</em> or <em>modules</em>.
    If you don't know what to search check all the <a class="toggleTemplate" href="<?php echo $this->getDownloadConfigAsTextUrl() ?>">configuration keys</a>.
</p>

<script type="text/javascript">
    function searchConfiguration() {
        new Ajax.Updater(
            'config-search-results',
            '<?php echo $this->getSearchConfigUrl() ?>',
            {
                method: 'post',
                parameters: Form.serialize($('config-search-form'))
            });
        return false;
    }
</script>

<div id="config-search-results">
    <table>
        <thead>
        <tr>
            <th><?php echo $this->__('#') ?></th>
            <th><?php echo $this->__('Config') ?></th>
            <th><?php echo $this->__('Value') ?></th>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
