<?php
/** @var Sheep_Debug_Block_Controller $this */

$info = $this->getController();
$cookies = $info->getCookies();
$session = $info->getSession();
$getParameters = $info->getGetParameters();
$postParameters = $info->getPostParameters();

?>
<h4><?php $this->__('Controller information') ?></h4>
<table>
    <thead>
    <tr>
        <th><?php echo $this->__('Variable') ?></th>
        <th><?php echo $this->__('Value') ?></th>
    </tr>
    </thead>
    <tbody>
    <tr class="djDebugOdd">
        <td><?php echo $this->__('Route Name') ?></td>
        <td><?php echo $this->escapeHtml($info->getRouteName()) ?></td>
    </tr>
    <tr class="djDebugEven">
        <td><?php echo $this->__('Controller Module') ?></td>
        <td><?php echo $this->escapeHtml($info->getModule()) ?></td>
    </tr>
    <tr class="djDebugOdd">
        <td><?php echo $this->__('Controller Class') ?></td>
        <td><?php echo $this->escapeHtml($info->getReference()) ?></td>
    </tr>
    <tr class="djDebugEven">
        <td><?php echo $this->__('Request Path') ?></td>
        <td><?php echo $info->getPath() ?></td>
    </tr>
    </tbody>
</table>

<h4><?php echo $this->__('COOKIES Variables') ?></h4>
<?php if ($cookies): ?>
    <table>
        <colgroup>
            <col style="width:20%"/>
            <col/>
        </colgroup>
        <thead>
        <tr>
            <th><?php echo $this->__("Variable") ?></th>
            <th><?php echo $this->__("Value") ?></th>
        </tr>
        </thead>
        <tbody>
        <?php $row = 0; ?>
        <?php foreach ($cookies as $key => $value): ?>
            <tr class="<?php echo(($row % 2 ? 'djDebugOdd' : 'djDebugEven')) ?>">
                <td><?php echo htmlspecialchars($key) ?></td>
                <td><?php echo htmlspecialchars($value) ?></td>
            </tr>
            <?php $row++; ?>
        <?php endforeach ?>
        </tbody>
    </table>
<?php else: ?>
    <p><?php echo $this->__("No COOKIE data") ?></p>
<?php endif ?>

<h4><?php echo $this->__('SESSION Variables') ?></h4>
<?php if (count($session)): ?>
    <table>
        <colgroup>
            <col style="width:20%"/>
            <col/>
        </colgroup>
        <thead>
        <tr>
            <th><?php echo $this->__('Variable') ?></th>
            <th><?php echo $this->__('Value') ?></th>
        </tr>
        </thead>
        <?php foreach ($session as $namespace => $data): ?>
            <tbody>
                <?php if (is_array($data)): ?>
                    <tr><th colspan="2" style="text-align: center; font-size: 120%; font-weight: bold;"><?php echo $this->escapeHtml($namespace) ?></th></tr>
                    <?php $row = 0; ?>
                    <?php foreach ($data as $key => $value): ?>
                        <tr class="<?php echo $row % 2 ? 'djDebugOdd' : 'djDebugEven' ?>">
                            <td><?php echo $this->escapeHtml($key) ?></td>
                            <td>
                                <?php if (is_array($value)): ?>
                                    <?php foreach ($value as $valueKey => $valueContent): ?>
                                        <?php echo $this->escapeHtml($valueKey) . ' => ' . $this->escapeHtml($valueContent) ?><br/>
                                    <?php endforeach; ?>
                                <?php elseif (is_object($value)): ?>
                                    <?php echo get_class($value) ?>
                                <?php else: ?>
                                    <?php echo $this->escapeHtml($value) ?>
                                <?php endif ?>
                            </td>
                        </tr>
                        <?php $row++; ?>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($namespace) ?></td>
                        <td><?php echo $this->escapeHtml(var_export($data, true)) ?></td>
                    </tr>
                <?php endif; ?>
            </tbody>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <p><?php echo $this->__('No SESSION data') ?></p>
<?php endif ?>

<h4><?php echo $this->__('GET Variables') ?></h4>
<?php if ($getParameters): ?>
    <table>
        <thead>
        <tr>
            <th><?php echo $this->__('Variable') ?></th>
            <th><?php echo $this->__('Value') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php $row = 0; ?>
        <?php foreach ($getParameters as $key => $value): ?>
            <tr class="<?php echo $row % 2 ? 'djDebugOdd' : 'djDebugEven' ?>">
                <td><?php echo $this->escapeHtml($key) ?></td>
                <td><?php echo $this->escapeHtml(var_export($value, true)) ?></td>
            </tr>
            <?php $row++; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p><?php echo $this->__('No GET data') ?></p>
<?php endif ?>

<h4><?php echo $this->__('POST Variables') ?></h4>
<?php if ($postParameters): ?>
    <table>
        <thead>
        <tr>
            <th><?php echo $this->__('Variable') ?></th>
            <th><?php echo $this->__('Value') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php $row = 0; ?>
        <?php foreach ($postParameters as $key => $value): ?>
            <tr class="<?php echo $row % 2 ? 'djDebugOdd' : 'djDebugEven' ?>">
                <td><?php echo $this->escapeHtml($key) ?></td>
                <td><?php echo $this->escapeHtml(var_export($value, true)) ?></td>
            </tr>
            <?php $row++; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p><?php echo $this->__('No POST data') ?></p>
<?php endif ?>
