<?php
/** @var Sheep_Debug_Block_Array $this */

$data = $this->getArray();
?>
<div class="djDebugPanelTitle">
    <a class="djDebugClose djDebugBack" href="#"><?php echo $this->__('Back'); ?></a>
    <h3><?php echo $this->escapeHtml($this->getTitle()) ?></h3>
</div>

<div class="djDebugPanelContent">
    <div class="scroll">
        <h4><?php echo $this->escapeHtml($this->getTitle()) ?></h4>

        <table>
            <tbody>
            <?php $row = 0; ?>
            <?php foreach ($data as $key => $childData): ?>
                <tr class="<?php echo $row % 2 ? 'djDebugOdd' : 'djDebugEven' ?>">
                    <th><h5><?php echo $this->escapeHtml($key) ?></h5></th>
                </tr>

                <?php if (is_array($childData)): ?>
                    <?php if ($childData): ?>
                        <?php foreach ($childData as $value): ?>
                            <tr class="<?php echo $row % 2 ? 'djDebugOdd' : 'djDebugEven' ?>">
                                <td>
                                    <code><?php echo $this->escapeHtml($value) ?></code>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr class="<?php echo $row % 2 ? 'djDebugOdd' : 'djDebugEven' ?>"><td><?php echo $this->__('No Data'); ?></td></tr>
                    <?php endif; ?>
                <?php else: ?>
                    <tr class="<?php echo $row % 2 ? 'djDebugOdd' : 'djDebugEven' ?>">
                        <td><?php echo $childData ? $this->escapeHtml($childData) : $this->__('No Data') ?></td>
                    </tr>
                <?php endif; ?>

                <?php $row++; ?>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>
