<h4><?php echo $this->__('View content of logs file'); ?></h4>

<a class="remoteCall toggleTemplate"
   href="<?php echo Mage::getUrl('debug/index/viewLog', array('file' => Mage::getStoreConfig('dev/log/file'))); ?>">
    <?php echo Mage::getStoreConfig('dev/log/file'); ?>
</a>
<a class="remoteCall toggleTemplate"
   href="<?php echo Mage::getUrl('debug/index/viewLog', array('file' => Mage::getStoreConfig('dev/log/exception_file'))); ?>">
    <?php echo Mage::getStoreConfig('dev/log/exception_file'); ?>
</a>