<?php
/** @var Sheep_Debug_Block_Panel $this */
?>

<div class="djDebugPanelTitle">
    <a class="djDebugClose djDebugBack" href="">"Back"</a> 
    <h3><?php echo $this->escapeHtml($this->getTitle()) ?></h3>
</div> 
<div class="djDebugPanelContent"> 
    <div class="scroll"> 
        <code><?php echo $this->getIsContentSafe() ? $this->getContent() : $this->escapeHtml($this->getContent()) ?></code>
    </div> 
</div>
