<?php
/* @var $this Sheep_Debug_Block_Toolbar */

$panels = $this->getVisiblePanels();
?>

<h2>Toolbar</h2>

<style type="text/css">@media print { #djDebug {display:none;}}</style>
<script type="text/javascript">
// <![CDATA[
var DEBUG_TOOLBAR_MEDIA_URL = "<?php echo $this->getDebugMediaUrl(); ?>";
// ]]>
</script>
<script type="text/javascript" src="<?php echo $this->getDebugMediaUrl(); ?>js/toolbar.js"></script>

<div id="djDebug" style="display:none;">
	<div style="display:none;" id="djDebugToolbar">
		<ul id="djDebugPanelList">
            <?php if( $panels ): ?>
            <li><a id="djHideToolBarButton" href="#" title="<?php echo $this->__('Hide Toolbar'); ?>"><?php echo $this->__('Hide') ?> &raquo;</a></li>
            <?php else: ?>
			<li id="djDebugButton"><?php echo $this->__('DEBUG'); ?></li>
            <?php endif; ?>

            <?php foreach ($panels as $panel): ?>
				<li>
                    <?php if($panel->hasContent()): ?>
                        <a href="<?php echo $panel->getContentUrl() ?: '#' ?>" title="<?php $this->escapeHtml($this->__($panel->getTitle())) ?>" class="<?php echo $panel->getContentId() ?>">
                    <?php else: ?>
					    <div class="contentless">
                    <?php endif; ?>

                    <?php echo $this->escapeHtml($this->__($panel->getTitle())) ?>

                    <?php if($panel->getSubTitle()): ?>
                        <br /><small><?php echo $this->escapeHtml($this->__($panel->getSubTitle())) ?></small>
                    <?php endif; ?>

                    <?php if($panel->hasContent()): ?>
                        </a>
                    <?php else: ?>
                        </div>
                    <?php endif; ?>
				</li>
            <?php endforeach; ?>

            <li>
                <a href="#" class="">
                    <?php echo $this->__('About'); ?><br/>
                    <small><?php echo $this->__('Version %s', $this->getVersion()) ?></a></small>
                </a>
            </li>
		</ul>
	</div>

	<div style="display:none;" id="djDebugToolbarHandle">
        <a title="<?php echo $this->__('Show Toolbar'); ?>" id="djShowToolBarButton" href="#">&laquo;</a>
	</div>

    <?php
    /** @var Sheep_Debug_Block_Panel $panel */
    foreach ($this->getSortedChildBlocks() as $panel): ?>
        <?php if($panel->hasContent()): ?>
            <div id="<?php echo $panel->getContentId() ?>" class="panelContent">
                <div class="djDebugPanelTitle">
                    <a href="" class="djDebugClose"><?php echo $this->__('Close'); ?></a>
                    <h3><?php echo $this->escapeHtml($this->__($panel->getTitle())) ?></h3>
                </div>
                <div class="djDebugPanelContent">
                    <div class="scroll">
                        <?php echo $panel->toHtml() ?>
                    </div>
                </div>
            </div>
        <?php endif; ?>

    <?php endforeach; ?>
	<div id="djDebugWindow" class="panelContent"></div>
</div>
