<?php
/** @var Sheep_Debug_Block_Util $this */
?>

<h4><?php echo $this->__('Quick Links') ?></h4>

<p>
    <button class="button postButton" data-href="<?php echo $this->getFlushCacheUrl() ?>">
        <?php echo $this->__('Flush Cache'); ?>
    </button>
    <?php if ($this->isTemplateHintsEnable()): ?>
        <button class="button postButton" data-href="<?php echo $this->getDisableTemplateHintsUrl() ?>">
            <?php echo $this->__('Disable Template Hints'); ?>
        </button>
    <?php else: ?>
        <button class="button postButton" data-href="<?php echo $this->getEnableTemplateHintsUrl() ?>">
            <?php echo $this->__('Enable Template Hints'); ?>
        </button>
    <?php endif; ?>

    <?php if ($this->isTranslateInlineEnable()): ?>
        <button href="#" class="button postButton" data-href="<?php echo $this->getDisableTranslateUrl() ?>">
            <?php echo $this->__('Disable Inline Translation'); ?>
        </button>
    <?php else: ?>
        <button href="#" class="button postButton" data-href="<?php echo $this->getEnableTranslateUrl() ?>">
            <?php echo $this->__('Enable Inline Translation'); ?>
        </button>
    <?php endif; ?>
</p>

<h4><?php echo $this->__('Grouped Class Search'); ?></h4>

<form action="#" id="class-search-form" onSubmit="submitGroupedClassSearch(); return false;">
    <input name="uri" class="input-text required-entry" type="search" size="40"/>
    <select name="group" class="input-select required-entry">
        <option>all</option>
        <option>model</option>
        <option>block</option>
        <option>helper</option>
    </select>

    <button class="button" onClick="submitGroupedClassSearch()"><?php echo $this->__('Search Grouped Class') ?></button>
</form>

<p>
    <?php echo $this->__('Search examples:') ?> <em>catalog/product</em>, <em>core/url</em>
</p>

<script type="text/javascript">
    function submitGroupedClassSearch() {
        var request = new Ajax.Updater(
            'class-search-results',
            '<?php echo Mage::helper('sheep_debug/url')->getSearchGroupClassUrl() ?>',
            {
                method: 'post',
                parameters: Form.serialize($('class-search-form'))
            });
    }

    // Registers any buttons
    $$('.postButton').each(function (el) {
        return el.observe('click', function () {
            new Ajax.Request(this.getAttribute('data-href'), {
                method: 'post',
                onSuccess: function () {
                    location.reload();
                },
                onFailure: function (transport) {
                    alert(transport.responseText);
                }
            });
        })
    });


</script>

<div id="class-search-results">
    <table>
        <thead>
        <tr>
            <th><?php echo $this->__('#') ?></th>
            <th><?php echo $this->__('Group Type') ?></th>
            <th><?php echo $this->__('Class') ?></th>
            <th><?php echo $this->__('File path') ?></th>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
