<?php
?>

<h4><?php echo $this->__('Quick Links') ?></h4>
<p>
    Some links
</p>

<h4><?php echo $this->__('Grouped Class Search'); ?></h4>

<form action="#" id="class-search-form" onSubmit="submitGroupedClassSearch(); return false;">
    <input name="uri" class="input-text required-entry" type="search" size="40"/>
    <select name="group" class="input-select required-entry">
        <option>all</option>
        <option>model</option>
        <option>block</option>
        <option>helper</option>
    </select>

    <button class="button" onClick="submitGroupedClassSearch()"><?php echo $this->__('Search Grouped Class') ?></button>
</form>

<p>
    <?php echo $this->__('Search examples:') ?> <em>catalog/product</em>, <em>core/url</em>
</p>

<script type="text/javascript">
    function submitGroupedClassSearch() {
        var request = new Ajax.Updater(
            'class-search-results',
            '<?php echo Mage::helper('sheep_debug/url')->getSearchGroupClassUrl() ?>',
            {
                method: 'post',
                parameters: Form.serialize($('class-search-form'))
            });
    }
</script>

<div id="class-search-results">
    <table>
        <thead>
        <tr>
            <th><?php echo $this->__('#') ?></th>
            <th><?php echo $this->__('Group Type') ?></th>
            <th><?php echo $this->__('Class') ?></th>
            <th><?php echo $this->__('File path') ?></th>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
