<table>
	<thead>
		<tr>
            <th><?php echo $this->__("Module") ?></th>
            <th><?php echo $this->__("Version") ?></th>
            <th><?php echo $this->__("Status") ?></th>
            <th><?php echo $this->__("Actions") ?></th>
		</tr>
	</thead>
    <tbody>
        <?php $row = 0; ?>
        <?php foreach( $this->getItems() as $item ): ?>
            <tr class="<?php echo (($row % 2)?'djDebugOdd':'djDebugEven') ?>">
                <td><?php echo $item['module'] ?></td>
                <td><?php echo $item['version'] ?></td>
                <td><?php echo $item['active'] ?></td>
                <td><a class="remoteCall" href="<?php echo Mage::getUrl('debug/index/toggleModuleStatus', array('_query'=>array('module'=>$item['module']))) ?>">Toggle Status</a><td>
			</tr>
            <?php $row++; ?>
        <?php endforeach; ?>
	</tbody>
</table>
